---
title: "ECON 613 Reading Note 1"
author: "Yonghan Shi"
date: "1/25/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Focusing on the young lawyers in the United States as a representative of high-skilled professionals, this paper identifies gender gaps in performance, explores the possible causes of the performance gaps, and studies the impact of gender gaps in performance on the gaps in career outcomes. In general, the authors propose that there are gender gaps in performance between male and female lawyers, which are significantly affected by factors like having young children and aspirations for future careers. The performance gaps then result in earning and promotion gaps.

The authors first propose the puzzle asking why there are persistent earning gaps in the legal profession. They notice that the previous explanation of individual characteristics is not comprehensive, and the gender gaps in other professions are not well explained as well. Thus, they pay attention to the gender gaps in performance and try to answer this question from this channel. The well-established way of measuring performance in the legal industry makes it easier for scholars to evaluate young lawyers' performance. Hours billed and new client revenue become the indicators for lawyers' performance.

Based on such understandings, the paper makes two types of hypotheses. The first is the general hypothesis that there are gender gaps in the performance of young lawyers, which affect their earnings and promotion. The second concerns the possible cause of gender gaps in performance, including the widely believed reasons of discrimination, children rearing, and newly proposed causes of career aspirations and other gender differences. These hypotheses create a potential causal chain to explain the phenomenon. 

To test the hypotheses, the paper introduces the data from After the JD, which contains key variables indicating performances and other control variables such as time, education, and region. The authors run several linear regressions to find the relationship between variables, and then test the significance to validate the hypotheses. In some regressions, instrumental variables have been applied to solve the problem of endogeneity.

They start by identifying the gender gaps in performance. It is shown that holding other individual characteristics constant, there are significant differences in the two measurements of performance for female and male lawyers. Such differences cannot be explained by factors like target hours, hours worked, and specialty. Thus, the data verifies the existence of gender gaps in performance.

The paper then moves to the most important part that answers the question of what affects the gender gaps in performance. Starting with the hypothesis of discrimination, the authors regress several variables on performance including ones evaluating assignments, partner discounting, mentoring activities, contact with clients, and self-reported discrimination. The regression results show that they are either similar for males and females or not significant in determining their performance. Then, for the children rearing hypothesis, the paper finds out that rather than children numbers, having young children significantly affects young lawyers' performance gaps. It is worth noting that the influence of having young children is robust on hours billed but not robust on new client revenue, as the latter is mainly determined by factors like reputation. Comparisons and predictions are being used to rule out potential cross-sectional and timing selection issues. In addition to these two commonly believed causes, the paper also finds out that career aspiration has a strong positive effect on gender gaps in performance, while over-billing, networking, and working on weekends are not the main reasons for gender gaps.

In the last part of the article, the authors evaluate the influence of performance gaps on earnings and promotions respectively. On the one hand, after comparing the analyses with and without controlling for performance measures, it is shown that performance gaps result in earning gaps between genders. On the other hand, holding variables indicating individual and firm characteristics constant, performance gaps have a positive and significant effect on promotion gaps. 

In conclusion, the authors indicate that having young children and aspirations for future careers affect gender gaps in performance, which then impacts the gender gaps in career outcomes. The article still leaves some room for future research, for example, the differences between the different levels of lawyers mentioned in the article are not explained in detail. The correlations between the different explanatory variables also need further elucidation, for example having children may have an impact on career aspirations. As the study was conducted on practicing lawyers and did not mention the barriers for women entering the profession, implicit discrimination may still be present in this male-dominated profession, thus determining performance measurement.